version: '3.9'

services:
  api:
    container_name: api
    build: .
    ports:
      - 4444:8888
    environment:
      - DB_HOST=db
      - DB_PASSWORD=postgres
      - DB=db_entrega_S5_19
      - DB_USER=postgres
      - SECRET_KEY=segredo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_entrega_S5_19
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db_entrega_S5_19"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
   

